services:
    _defaults:
        autowire: true
        autoconfigure: true

    KPhoen\SitemapBundle\Command\GenerateSitemapCommand:
        arguments:
            $sitemap: '@SitemapGenerator\Sitemap'
        tags:
            - { name: console.command }

    KPhoen\SitemapBundle\Controller\SitemapController:
        public: true
        tags: [ 'controller.service_arguments' ]

    SitemapGenerator\Dumper\GzFile:
        arguments: [ "%sitemap.config.file%" ]

    SitemapGenerator\FileDumper: '@SitemapGenerator\Dumper\GzFile'

    SitemapGenerator\Formatter\Xml:

    SitemapGenerator\SitemapFormatter: '@SitemapGenerator\Formatter\Xml'

    SitemapGenerator\Sitemap:
        public: true
        arguments:
            $dumper: '@SitemapGenerator\FileDumper'
            $formatter: '@SitemapGenerator\SitemapFormatter'
